import Head from "next/head";
import { getSession, useSession } from "next-auth/react";
import Login from "@/components/Login";


export default function Home() {
const {data:session} = useSession();
if(!session) return <Login />;
  return (
    <>
      <Head>
        <title>Jojo-Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Jojo-Movies</h1>
      </main> 
    </>
  );
}

export async function getServerSideProps(context) { 
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
